build: false
version: dev-{build}
shallow_clone: false
clone_folder: C:\projects\php-cs-fixer

environment:
    matrix:
        - php_ver: 7.1.2
          TASK_TESTS_COVERAGE: 1

cache:
    - '%APPDATA%\Composer'
    - '%LOCALAPPDATA%\Composer'
    - C:\tools\php -> .appveyor.yml
    - C:\tools\composer.phar -> .appveyor.yml

init:
    - SET PATH=C:\tools\php;%PATH%
    - git config --global github.accesstoken 5e7538aa415005c606ea68de2bbbade0409b4b8c

install:
    - ps: Set-Service wuauserv -StartupType Manual
    - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
    - IF NOT EXIST C:\tools\php (choco install --yes --allow-empty-checksums php --version %php_ver% --params '/InstallDir:C:\tools\php')
    - cd C:\tools\php
    - copy php.ini-production php.ini
    - echo date.timezone="UTC" >> php.ini
    - echo memory_limit=1G >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo curl.cainfo="C:\cacert.pem" >> php.ini
    - IF NOT EXIST C:\tools\composer.phar (cd C:\tools && appveyor DownloadFile https://getcomposer.org/download/1.4.1/composer.phar)
    - cd C:\projects\php-cs-fixer
    - php C:\tools\composer.phar global show -ND 2>1 | findstr "hirak/prestissimo" || php C:\tools\composer.phar global require hirak/prestissimo

before_test:
    - cd C:\projects\php-cs-fixer
    - php C:\tools\composer.phar update --no-interaction --no-progress --optimize-autoloader --no-ansi

test_script:
    - cd C:\projects\php-cs-fixer
    - IF NOT DEFINED TASK_TESTS_COVERAGE vendor\bin\phpunit --verbose
    - IF DEFINED TASK_TESTS_COVERAGE phpdbg -qrr vendor\phpunit\phpunit\phpunit --verbose --coverage-clover build\logs\clover.xml

after_test:
    - IF DEFINED TASK_TESTS_COVERAGE vendor\bin\coveralls -v
