language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: hhvm-3.3
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.6
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge

install:
    curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.11.1/php-cs-fixer.phar -o php-cs-fixer.phar

script:
    php php-cs-fixer.phar --dry-run -v --config-file=.php_cs fix
