language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    include:
        - php: 5.3
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    allow_failures:
        - php: 7.0

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

before_script:
    - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi

script:
    - phpunit --verbose $PHPUNIT_FLAGS
    - php php-cs-fixer --diff --dry-run -v fix

after_script:
    - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then php vendor/bin/coveralls -v; fi
