language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer
        - $HOME/bin

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--optimize-autoloader --no-interaction --no-progress"
        - COMPOSER_FLAGS=""

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

    # Composer: boost installation
    - composer global show hirak/prestissimo -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

jobs:
    include:
        - &STANDARD_TEST_JOB
            stage: Test
            php: 7.2
            install:
                - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
                - composer info -D | sort
            script:
                - vendor/bin/phpunit --stop-on-error --stop-on-failure --exclude-group covers-nothing

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 7.2
            env: COLLECT_COVERAGE=1
            script:
                - phpdbg -qrr vendor/bin/phpunit  --testsuite coverage --stop-on-error --stop-on-failure --exclude-group covers-nothing --coverage-clover build/logs/clover.xml
